#!/usr/bin/env ruby
# filepath: /Users/jeongcool/me/my-tech-blog/scripts/generate_posts.rb
require 'fileutils'
require 'date'

count = (ARGV[0] || 100).to_i
dir = File.expand_path("../_posts", __dir__)
FileUtils.mkdir_p(dir)

start_date = Date.new(2024,1,1)

count.times do |i|
  date = start_date + i
  title = "Test Post #{i+1}"
  slug = title.downcase.gsub(/[^a-z0-9]+/, '-').gsub(/^-|-$/, '')
  filename = "#{date.strftime('%Y-%m-%d')}-#{slug}.md"
  path = File.join(dir, filename)

  front = <<~MD
    ---
    layout: post
    title: "#{title}"
    date: #{date.strftime('%Y-%m-%d')} 10:00:00 +0900
    categories: test
    tags: [test, sample]
    excerpt: "Sample excerpt for #{title}."
    ---
  MD

  body = <<~MD
    #{front}

    This is autogenerated test post ##{i+1}.

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.

    ## Example Code

    ```ruby
    # Sample code block for #{title}
    puts "Hello from #{title}"
    ```

    More sample content...
  MD

  File.write(path, body)
  puts "Created #{path}"
end